FROM dordoka/rpi-java8
#FROM anapsix/alpine-java

MAINTAINER Reinhard Seiler

ENTRYPOINT ["java", "-jar", "/usr/share/rseiler/homepage.jar"]

ADD target/rseiler-homepage.jar /usr/share/rseiler/homepage.jar