sudo: required

language: java

services:
  - docker

before_install:
  - cat docker/config.json | sed 's/${env.DOCKER_USERNAME}/'"DOCKER_USERNAME"'/g' | sed 's/${env.DOCKER_PASSWORD}/'"$DOCKER_PASSWORD"'/g' > ~/.dockercfg

script:
  - mvn install
