sudo: required

language: java

services:
  - docker

script:
  - mvn install && cat docker/config.json | sed 's/${env.DOCKER_USERNAME}/'"DOCKER_USERNAME"'/g' | sed 's/${env.DOCKER_PASSWORD}/'"$DOCKER_PASSWORD"'/g' > ~/.dockercfg && dockerfile:push
