<#import "../../layout.ftl" as layout>
<@layout.default>
<h1>spBee - Stored Procedure Bee</h1>
<p>
    This framework allows to declare the stored procedures calls declarative instead of programmatically. Only the
    interfaces, the entities and add a few annotations need to be written. The code for the stored procedures, the
    necessary entity mappers and the implementations of the DAO interfaces is generated by spBee.
    It's also possible to use abstract classes instead of interfaces.
</p>
<p>
    An important point is that there is no magic behind this framework like JPA/Hibernate with crazy reflection,
    proxies and framework logic. The only logic is how to translate the annotations to the corresponding Java code.
    Thereby spBee has only about 1700 LoC (measured with <a href="https://www.npmjs.com/package/sloc">sloc</a>).
</p>
<p>
    Everything is done at compile time. Therefore there is no performance shortcoming. No reflection. No proxies.
</p>

<h2>Documentation</h2>
<p>
    Visit the documentation at:
    <a href="https://rseiler.github.io/spBee/index.html" target="_blank">Latest Documentation</a>
</p>

<h2>Source Code</h2>
<p>The source is hosted on <a href="https://github.com/rseiler/spBee" target="_blank">GitHub</a></p>

<h2>License</h2>
<p>
    spBee is licensed under the terms of the
    <a href="https://www.apache.org/licenses/LICENSE-2.0.html" target="_blank">Apache License, Version 2.0</a>
</p>

<h2>Thank you!</h2>
<p>
    I really appreciate all kind of feedback and contributions. Thanks for using and supporting spBee.
</p>
</@layout.default>